In [8]:
import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install pandas
import pandas as pd
import numpy as np

Requirement already satisfied: numpy in c:\project\learn\venv\lib\site-packages (1.24.1)
Requirement already satisfied: pandas in c:\project\learn\venv\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\project\learn\venv\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\project\learn\venv\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in c:\project\learn\venv\lib\site-packages (from pandas) (1.24.1)
Requirement already satisfied: six>=1.5 in c:\project\learn\venv\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [12]:
df = pd.read_csv('data.csv')

In [15]:
print(df)

     IndicatorCode                                     Indicator ValueType  \
0     NCD_BMI_MEAN  Mean BMI (kg/m²) (age-standardized estimate)   numeric
1     NCD_BMI_MEAN  Mean BMI (kg/m²) (age-standardized estimate)   numeric
2     NCD_BMI_MEAN  Mean BMI (kg/m²) (age-standardized estimate)   numeric
3     NCD_BMI_MEAN  Mean BMI (kg/m²) (age-standardized estimate)   numeric
4     NCD_BMI_MEAN  Mean BMI (kg/m²) (age-standardized estimate)   numeric
...            ...                                           ...       ...
2875  NCD_BMI_MEAN  Mean BMI (kg/m²) (age-standardized estimate)   numeric
2876  NCD_BMI_MEAN  Mean BMI (kg/m²) (age-standardized estimate)   numeric
2877  NCD_BMI_MEAN  Mean BMI (kg/m²) (age-standardized estimate)   numeric
2878  NCD_BMI_MEAN  Mean BMI (kg/m²) (age-standardized estimate)   numeric
2879  NCD_BMI_MEAN  Mean BMI (kg/m²) (age-standardized estimate)   numeric

     ParentLocationCode         ParentLocation Location type  \
0                   AFR                 Africa       Country
1                   AFR                 Africa       Country
2                   AFR                 Africa       Country
3                   AFR                 Africa       Country
4                   AFR                 Africa       Country
...                 ...                    ...           ...
2875                AMR               Americas       Country
2876                EMR  Eastern Mediterranean       Country
2877                EMR  Eastern Mediterranean       Country
2878                EMR  Eastern Mediterranean       Country
2879                WPR        Western Pacific       Country

     SpatialDimValueCode          Location Period type  Period  ...  \
0                    ETH          Ethiopia        Year    2016  ...
1                    ERI           Eritrea        Year    2016  ...
2                    ETH          Ethiopia        Year    2016  ...
3                    ERI           Eritrea        Year    2016  ...
4                    MDG        Madagascar        Year    2016  ...
...                  ...               ...         ...     ...  ...
2875                 LCA       Saint Lucia        Year    2012  ...
2876                 EGY             Egypt        Year    2012  ...
2877                 IRQ              Iraq        Year    2012  ...
2878                 KWT            Kuwait        Year    2012  ...
2879                 MHL  Marshall Islands        Year    2012  ...

      FactValueUoM FactValueNumericLowPrefix FactValueNumericLow  \
0              NaN                       NaN                19.0
1              NaN                       NaN                19.2
2              NaN                       NaN                19.8
3              NaN                       NaN                19.9
4              NaN                       NaN                19.9
...            ...                       ...                 ...
2875           NaN                       NaN                28.5
2876           NaN                       NaN                28.8
2877           NaN                       NaN                28.5
2878           NaN                       NaN                28.9
2879           NaN                       NaN                28.4

     FactValueNumericHighPrefix FactValueNumericHigh               Value  \
0                           NaN                 21.0      20.1 [19 – 21]
1                           NaN                 21.3  20.2 [19.2 – 21.3]
2                           NaN                 21.3  20.6 [19.8 – 21.3]
3                           NaN                 21.5  20.7 [19.9 – 21.5]
4                           NaN                 22.3  21.1 [19.9 – 22.3]
...                         ...                  ...                 ...
2875                        NaN                 29.7  29.1 [28.5 – 29.7]
2876                        NaN                 29.4  29.1 [28.8 – 29.4]
2877                        NaN                 29.9  29.2 [28.5 – 29.9]
2878                        NaN                 29.5  29.2 [28.9 – 29.5]
2879                        NaN                 30.4  29.4 [28.4 – 30.4]

     FactValueTranslationID  FactComments  Language              DateModified
0                       NaN           NaN        EN  2017-09-26T18:30:00.000Z
1                       NaN           NaN        EN  2017-09-26T18:30:00.000Z
2                       NaN           NaN        EN  2017-09-26T18:30:00.000Z
3                       NaN           NaN        EN  2017-09-26T18:30:00.000Z
4                       NaN           NaN        EN  2017-09-26T18:30:00.000Z
...                     ...           ...       ...                       ...
2875                    NaN           NaN        EN  2017-09-26T18:30:00.000Z
2876                    NaN           NaN        EN  2017-09-26T18:30:00.000Z
2877                    NaN           NaN        EN  2017-09-26T18:30:00.000Z
2878                    NaN           NaN        EN  2017-09-26T18:30:00.000Z
2879                    NaN           NaN        EN  2017-09-26T18:30:00.000Z

[2880 rows x 34 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   IndicatorCode               2880 non-null   object
 1   Indicator                   2880 non-null   object
 2   ValueType                   2880 non-null   object
 3   ParentLocationCode          2880 non-null   object
 4   ParentLocation              2880 non-null   object
 5   Location type               2880 non-null   object
 6   SpatialDimValueCode         2880 non-null   object
 7   Location                    2880 non-null   object
 8   Period type                 2880 non-null   object
 9   Period                      2880 non-null   int64
 10  IsLatestYear                2880 non-null   bool
 11  Dim1 type                   2880 non-null   object
 12  Dim1                        2880 non-null   object
 13  Dim1ValueCode               2880 non-null   object
 14  Dim2 type                   2880 non-null   object
 15  Dim2                        2880 non-null   object
 16  Dim2ValueCode               2880 non-null   object
 17  Dim3 type                   0 non-null      float64
 18  Dim3                        0 non-null      float64
 19  Dim3ValueCode               0 non-null      float64
 20  DataSourceDimValueCode      0 non-null      float64
 21  DataSource                  0 non-null      float64
 22  FactValueNumericPrefix      0 non-null      float64
 23  FactValueNumeric            2832 non-null   float64
 24  FactValueUoM                0 non-null      float64
 25  FactValueNumericLowPrefix   0 non-null      float64
 26  FactValueNumericLow         2832 non-null   float64
 27  FactValueNumericHighPrefix  0 non-null      float64
 28  FactValueNumericHigh        2832 non-null   float64
 29  Value                       2880 non-null   object
 30  FactValueTranslationID      48 non-null     float64
 31  FactComments                48 non-null     object
 32  Language                    2880 non-null   object
 33  DateModified                2880 non-null   object
dtypes: bool(1), float64(13), int64(1), object(19)
memory usage: 745.4+ KB